### ISSUE TITLE
Version 2.0.0 Tracking Issue

### ISSUE THREAD

**Issue by ShaishavGandhi** [uber/RxDogTag#56]
Checklist

- [x] Upgrade to RxJava 3 and AutoDispose 2
- [x] Package rename to `rxdogtag2`
- [x] Update Mkdocs to publish both 1.x and 2.x APIs
- [x] Update maven coords to `rxdogtag2`
- [ ] Update benchmark with RxJava 3

**Comment by ZacSweers** [comment]
Gonna close this out for now, the benchmark should be updated at some point but it's also likely unchanged
